A new folder wordSearch Added #29
prathimacode-hub/Dev-Mint pull request #31
Opened 2023-12-25 15:32 UTC by RonitBaranwal

A word Search application has been added which uses apis to search for English words .

CodePeak 2023 Participant

Closes: #30 number that will be closed through this PR

2023-12-25 16:51 UTC, prathimacode-hub requested changes
Keep your folder name as "Dictionary Word Search". While creating Issues / PRs please use the template formats given in repository README file. Also include the README.md file using this [template](https://github.com/prathimacode-hub/Dev-Mint/blob/main/.github/README_TEMPLATE.md). Add your output screenshots in your PR. @RonitBaranwal

2023-12-26 06:12 UTC, RonitBaranwal commented
Okay will do it .

2023-12-31 09:22 UTC, prathimacode-hub commented
Have you done the changes? @RonitBaranwal

2023-12-31 11:32 UTC, RonitBaranwal commented
Sorry,i was caught up in certain tasks of my own .
Will it be okay if I make prs now?

2023-12-31 12:16 UTC, prathimacode-hub commented
Yes, you can make a PR now. And request to the team for the consideration of a PR. Since final leaderboard is still in the progress. Let me know once you're done with it. @RonitBaranwal

2025-02-07 14:46 UTC, closed without merging